version: "3.9"
services:
  helloworld:
    container_name: gs-spring-boot-docker
    build:
      context: ./.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: gs-spring-boot-docker-img:latest


